interface OpenAPISpec {
  info: { title: string; version: string };
  paths: Record<string, Record<string, any>>;
  components?: { schemas?: Record<string, any> };
}

function schemaToTs(schema: any, name: string, indent = 0): string {
  if (!schema) return "unknown";
  const pad = "  ".repeat(indent);
  if (schema.$ref) {
    return schema.$ref.replace("#/components/schemas/", "");
  }
  switch (schema.type) {
    case "string":  return schema.enum ? schema.enum.map((e: string) => `"${e}"`).join(" | ") : "string";
    case "integer":
    case "number":  return "number";
    case "boolean": return "boolean";
    case "array":   return `${schemaToTs(schema.items, name)}[]`;
    case "object": {
      if (!schema.properties) return "Record<string, unknown>";
      const props = Object.entries(schema.properties as Record<string, any>).map(([k, v]) => {
        const req = (schema.required ?? []).includes(k) ? "" : "?";
        return `${pad}  ${k}${req}: ${schemaToTs(v, k, indent + 1)};`;
      });
      return `{\n${props.join("\n")}\n${pad}}`;
    }
    default: return "unknown";
  }
}

export function generateClient(spec: OpenAPISpec): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by APIBlueprint\n");

  if (spec.components?.schemas) {
    for (const [name, schema] of Object.entries(spec.components.schemas)) {
      lines.push(`export interface ${name} ${schemaToTs(schema, name)}\n`);
    }
  }

  const tagGroups: Record<string, any[]> = {};
  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, op] of Object.entries(methods)) {
      const tag = (op.tags?.[0] ?? "Default").replace(/[^a-zA-Z]/g, "");
      if (!tagGroups[tag]) tagGroups[tag] = [];
      tagGroups[tag].push({ method: method.toUpperCase(), path, op });
    }
  }

  lines.push(`const BASE_URL = "";\n`);
  lines.push(`async function request<T>(method: string, path: string, body?: unknown): Promise<T> {`);
  lines.push(`  const res = await fetch(BASE_URL + path, {`);
  lines.push(`    method, headers: { "Content-Type": "application/json" },`);
  lines.push(`    body: body ? JSON.stringify(body) : undefined,`);
  lines.push(`  });`);
  lines.push(`  if (!res.ok) throw new Error(\`\${method} \${path} → \${res.status}\`);`);
  lines.push(`  return res.json();`);
  lines.push(`}\n`);

  for (const [tag, ops] of Object.entries(tagGroups)) {
    lines.push(`export const ${tag}Api = {`);
    for (const { method, path, op } of ops) {
      const fnName = op.operationId ?? `${method.toLowerCase()}${path.replace(/[^a-zA-Z]/g, "_")}`;
      const hasBody = ["POST", "PUT", "PATCH"].includes(method);
      const pathParams = (path.match(/\{(\w+)\}/g) ?? []).map((p: string) => p.slice(1, -1));
      const paramStr = [
        ...pathParams.map((p: string) => `${p}: string | number`),
        ...(hasBody ? ["body?: unknown"] : []),
      ].join(", ");
      const resolvedPath = path.replace(/\{(\w+)\}/g, (_: string, k: string) => `\${${k}}`);
      lines.push(`  ${fnName}: (${paramStr}) => request(\`${resolvedPath}\`, "${method}"${hasBody ? ", body" : ""}),`);
    }
    lines.push(`};\n`);
  }

  return lines.join("\n");
}
